### ISSUE TITLE
Feature 1 – Login and User registration

### ISSUE THREAD

**Issue by Chatur19005** [Chatur19005/LibrarySystem#1]
Library staff should be able to register with the system by providing their user ID, firstname,
lastname, username, password, and email address.
o Validation: Passwords must be more than 8 digits. Registration will be ignored if the
password is less than 8 digits. Email and username need to be checked for existing
registrations before submission, provided email also needs to validate over correct
format.
o Validation: The user ID should be created in the 'U<BOOK_ID>' format only (e.g., U001).
If the user sets another text format as the User ID, that record should not be submitted
to the system. (Hint: Use Regular Expressions).
❖ Other features should be inside the admin panel. Access to these features is granted only after
logging in to the system. (Hint: PHP sessions can be used.)
❖ User details (user ID, firstname, lastname, username, password, email address) need to be
updated individually once they are added to the system.
❖ Each user should log in to the system using their specific username and password registered with
the system.
❖ User details need to be deleted and updated individually.
❖ User records should be visible in a table with columns for user ID, firstname, lastname,
username, password, and email address.
❖ User should be able to logout from the system.
❖ Extra marks (optional) – You can use any hashing technique (SHA128, MD5…) to store passwords

**Comment by hasitha-2000** [comment]
developed the login issue

**Comment by hasitha-2000** [comment]
developed the login issue
